### ISSUE TITLE
High level design

### ISSUE THREAD

**Issue by teamco** [teamco/hflow#1]
![hflow drawio](https://user-images.githubusercontent.com/18106/133925914-13c9bff9-b5ec-4643-8148-8410dcfaffdb.png)

**Comment by teamco** [comment]
[hflow.drawio.zip](https://github.com/teamco/hflow/files/7191998/hflow.drawio.zip)

**Comment by teamco** [comment]
[BuySell.drawio.zip](https://github.com/teamco/hflow/files/7192027/BuySell.drawio.zip)
[hflow.drawio.zip](https://github.com/teamco/hflow/files/7192028/hflow.drawio.zip)

**Comment by Dennimir** [comment]
![Info Diagram](https://user-images.githubusercontent.com/33101878/135756537-d621d16f-fd8b-4485-93e5-2da695416ea6.png)
